### ISSUE TITLE
Roadmap 3.2

### ISSUE THREAD

**Issue by vmarc** [vmarc/knooppuntnet#166]
### Samenvatting van de belangrijkste veranderingen in v3.1:
- aan te vullen

### Samenvatting van de belangrijkste veranderingen in v3.2:
- aan te vullen

### Zaken nog op te lossen in release v3.2:

- [ ] #150 planner gaat tegen enkele richting in
- [ ] #126 routes met alle knooppunten dezelfde naam
- [ ] #153 routes met alle knooppunten dezelfde naam
- [ ] #114 routes met alle knooppunten dezelfde naam
- [ ] #109 routes met alle knooppunten dezelfde naam
- [ ] #2 routes met alle knooppunten dezelfde naam
- [ ] #71 routes met overlappende wegen
- [ ] #4 routes met tussenliggende knooppunten
- [ ] #117 logica rond expected_??n_route_relations
- [ ] #102 knooppunten met naam in plaats van nummer
- [ ] #121 verbeteren foutafhandeling in planner
- [ ] nieuwe route naam tags tonen in 'standaard tags' in plaats van 'extra tags'
- [ ] verander link naar knooppuntpagina in plaats van routepagina in [NodeInvalidSurveyDate](https://experimental.knooppuntnet.nl/en/analysis/cycling/de/facts/NodeInvalidSurveyDate)
- [ ] beslissen hoe om te gaan met route=mbt [voorbeeld](https://experimental.knooppuntnet.nl/nl/analysis/route/11985472)
- [ ] gebruik tabel in [knooppuntwezen](https://experimental.knooppuntnet.nl/nl/analysis/cycling/de/orphan-nodes) pagina (+ filter)
- [ ] gebruik tabel in [Vrij routes](https://experimental.knooppuntnet.nl/nl/analysis/cycling/de/orphan-routes) pagina (+ filter)
- [ ] toon node naam in [locatie knooppunt](https://experimental.knooppuntnet.nl/en/analysis/cycling/nl/Drenthe/nodes) pagina
- [ ] voeg integriteits-indicator toe in [locatie knooppunt](https://experimental.knooppuntnet.nl/en/analysis/cycling/nl/Drenthe/nodes) pagina
- [ ] voeg opengenomen-in-route-relatie-indicator toe in [locatie knooppunt](https://experimental.knooppuntnet.nl/en/analysis/cycling/nl/Drenthe/nodes) pagina
- [ ] voeg filter toe in [locatie knooppunt](https://experimental.knooppuntnet.nl/en/analysis/cycling/nl/Drenthe/nodes) pagina
- [ ] voeg filter toe in [locatie routes](https://experimental.knooppuntnet.nl/en/analysis/cycling/nl/Drenthe/routes) pagina
- [ ] filter wordt initieel niet getoond in [Routewezen](https://experimental.knooppuntnet.nl/nl/analysis/cycling/de/orphan-routes) pagina, wel na wisselen van tab
- [ ] filter wordt initieel niet getoond in [Nodewezen](https://experimental.knooppuntnet.nl/nl/analysis/cycling/de/orphan-nodes) pagina, wel na wisselen van tab
- [ ] toon datum om aan te geven hoe recent/oud de achtergrondtegels zijn
- [ ] hernoemen van "Routewezen" naar "Vrije routes"
- [ ] evalueren of RouteInvalidSortingOrder terug ingevoerd wordt
- [ ] stats.route-node-name-mismatch.comment: omgekeerde volgorde is nu toch toegestaan?
- [ ] foutafhandeling in route pagina: route niet gevonden
- [ ] vervolledigen van de vertalingen in POEditor
- [ ] tekstaanpassing RouteWithoutNodes
- [ ] tekstaanpassing RouteNodeNameMismatch
- [ ] tekstaanpassing stats.route-unexpected-node.comment
- [ ] wiki paginas voor verschillende talen aanpassen naar voorbeeld van [problemen](https://wiki.openstreetmap.org/wiki/NL:Knooppuntnet_problemen)

- [ ] na release: route [3946609](https://www.openstreetmap.org/relation/3946609) terug op actief zetten en rwn maken?
- [ ] na release: [9174227](https://experimental.knooppuntnet.nl/en/analysis/route/9174227/map) en [7776398](https://experimental.knooppuntnet.nl/en/analysis/route/7776398) samenvoegen? soortelijke gevallen opsporen?
- [ ] na release: [7175609](https://experimental.knooppuntnet.nl/nl/analysis/route/7175609/map) en [11047960](https://experimental.knooppuntnet.nl/nl/analysis/route/11047960) samenvoegen?

### Volgende zaken worden uitgesteld tot na release v3.2:
- [ ] verder verfijnen interessepunten
- [ ] hoogte profiel
- [ ] kasseistroken
- [ ] toegankelijkheids regels / construction
- [ ] lange afstandsroutes monitor

**Comment by pelderson** [comment]
Mooie lijst! Wel lang ook....

**Comment by pelderson** [comment]
Vergis ik me of is het bijna zover?!

**Comment by vmarc** [comment]
Versie v3.2 is beschikbaar op [experimental.knooppuntnet.nl](https://experimental.knooppuntnet.nl) sinds 8 augustus. Misschien kun je daar eens doorlopen om te zien of alles in orde is. Dan zal ik daarna deze versie naar [knooppuntnet.nl](https://knooppuntnet.nl/) brengen.

Ondertussen ben ik volop bezig met de volgende release. Versie v4.0 zal vooral draaien rond erg fundamentele veranderingen achter de schermen (volledig andere database + route gebaseerde analyse in plaats van netwerk gebaseerde analyse).

**Comment by pelderson** [comment]
Een dingetje over de routenamen in geval van named nodes. De mappers vinden dat erg redundant, en dat ben ik met ze eens. Want: de namen staan al op de guideposts als name=..., die moeten dan overgebracht worden op de netwerk nodes als lwn_name=..., en dan ook nog eens in alle routes opgenomen worden in ofwel een van de naamvelden ofwel in from of to. Voor een node met drie routes betekent dat 5x precies dezelfde naam invoeren! 
De Fransen zouden liefst hebben dat de naam van de guidepost wordt overgenomen, ze voegen de guideposts meestal al toe aan de routes. De Duitsers doen dat ook, maar lijken geen probleem te hebben om de naam zelf als lwn_name in de nodes te zetten. Zij hebben ook meer ervaring met nodes waar géén guideposts staan. 
Mijn wens namens de mappers zou zijn dat de lwn_name op de node wel verplicht is (zodat het systeem ook zonder gemapte guideposts werkt), maar dat de name van de relatie wordt samengesteld uit de lwn_names en/of lwn_refs van de nodes (daar waar nu no_name verschijnt en een fout gemeld wordt.  Het is wel handig om in de analyse te kunnen zien (aan een typografisch kenmerk of een sterretje of zo) of de naam uit een routetag komt of dat hij samengesteld is uit node-tags.
(waar ik lwn schrijf bedoel ik natuurlijk ook alle andere scopes en transportmodes)

**Comment by pelderson** [comment]
Ik heb de eerste 6 issues getest, geen problemen gevonden!

**Comment by vmarc** [comment]
@pelderson De logica is ondertussen aangepast om de route naam af te leiden van de node namen als de route naam niet uit de route relatie tags gehaald kan worden. Dit is nog niet zo uitvoerig getest in de praktijk.

**Comment by pelderson** [comment]
> @pelderson De logica is ondertussen aangepast om de route naam af te leiden van de node namen als de route naam niet uit de route relatie tags gehaald kan worden. Dit is nog niet zo uitvoerig getest in de praktijk.

Kan ik het testen op experimental?

**Comment by vmarc** [comment]
> Kan ik het testen op experimental?

Ja, daar zou de aangepaste code moeten werken.

**Comment by pelderson** [comment]
Ik zie het werken op
https://experimental.knooppuntnet.nl/fr/analysis/route/12159666
Ook in de routelijst voor het netwerk.
De separatorstring is alleen een streepje, ik dacht dat Duitsers en Fransen
'- ' dus spatie-streepje-spatie gebruiken (zie de disused:name tag) omdat
hun namen vaak al een koppelstreepje bevatten. Maar dat staat misschien in
de vertalingen ergens?

Vr gr Peter Elderson


Op za 21 aug. 2021 om 14:05 schreef vmarc ***@***.***>:

**Comment by vmarc** [comment]
Code is verder aangepast zodat er extra spaties staan rond het streepje in de routenaam, behalve wanneer de node namen volledig uit cijfers bestaan (zo blijft 01-02 zonder spaties).

**Comment by pelderson** [comment]
In de toekomst verwacht ik nog issues die te maken hebben met gemengde situaties, dus knooppunten met een ..n_ref die verbonden worden met knooppunten met alleen een ..n_name. Voor nu zie ik daar geen praktijkvoorbeelden van maar gezien de ontwikkelingen in Duitsland verwacht ik dat dat daar wel gaat spelen. Voor nu is het zo goed, denk ik. Zodra het in produktie staat zal ik de fransen en duitsers ermee benaderen, en misschien kan @Matthijs (lees je nog mee?) het in Zwitserland aankaarten als mogelijkheid om een knooppuntplanner beschikbaar te krijgen. Want die is er nu niet!

**Comment by pelderson** [comment]
I can't wait to see this release live! The named nodes request for multimode named nodes is for later, I think, it hasn't been fully thought through yet.
